name: exam-2

services: 
  blog: 
    image: cmtabr/blog-crud
    build: 
      context: api
      dockerfile: Dockerfile
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    container_name: auth_service
    restart: always
    ports:
      - "5000:5000"
    volumes: 
      - ./api:/app
    networks:
      - service_network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M

  gateway:
    image: cmtabr/gateway
    build: 
      context: gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "3000:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - blog
    networks:
      - service_network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M

networks:
  service_network:
    driver: bridge